import { afterEach, describe, expect, it, vi } from 'vitest'
import { detectLanguage } from './detectLanguage'
import { kotori } from './kotori'

// tests are generated by AI, so they may not be perfect.

const mockNavigatorLanguages = (languages: string[]) => {
	Object.defineProperty(navigator, 'languages', {
		get: () => languages,
		configurable: true,
	})
}

let instance = kotori({ primary: 'en', secondaries: ['zh', 'ja'] })
let setLanguageSpy = vi.spyOn(instance, 'setLanguage')

afterEach(() => {
	vi.restoreAllMocks()
	instance = kotori({ primary: 'en', secondaries: ['zh', 'ja'] })
	setLanguageSpy = vi.spyOn(instance, 'setLanguage')
})

// ============================
// exact match
// ============================

describe('exact match', () => {
	it('sets language when browser language exactly matches primary', () => {
		mockNavigatorLanguages(['en'])
		detectLanguage(instance)

		expect(setLanguageSpy).toHaveBeenCalledWith('en')
		expect(setLanguageSpy).toHaveBeenCalledTimes(1)
	})

	it('sets language when browser language exactly matches a secondary', () => {
		mockNavigatorLanguages(['zh'])

		detectLanguage(instance)

		expect(setLanguageSpy).toHaveBeenCalledWith('zh')
		expect(setLanguageSpy).toHaveBeenCalledTimes(1)
	})

	it('matches the first preference in the browser list', () => {
		mockNavigatorLanguages(['ja', 'zh', 'en'])

		detectLanguage(instance)

		expect(setLanguageSpy).toHaveBeenCalledWith('ja')
		expect(setLanguageSpy).toHaveBeenCalledTimes(1)
	})

	it('skips non-matching preferences and matches later in the list', () => {
		mockNavigatorLanguages(['fr', 'de', 'zh'])

		detectLanguage(instance)

		expect(setLanguageSpy).toHaveBeenCalledWith('zh')
		expect(setLanguageSpy).toHaveBeenCalledTimes(1)
	})
})

// ============================
// subtag fallback
// ============================

describe('subtag fallback', () => {
	it('falls back to subtag by default when no exact match', () => {
		mockNavigatorLanguages(['zh-CN'])

		detectLanguage(instance)

		expect(setLanguageSpy).toHaveBeenCalledWith('zh')
		expect(setLanguageSpy).toHaveBeenCalledTimes(1)
	})

	it('falls back to subtag when fallbackToSubtag is true', () => {
		mockNavigatorLanguages(['zh-TW'])

		detectLanguage(instance, { fallbackToSubtag: true })

		expect(setLanguageSpy).toHaveBeenCalledWith('zh')
		expect(setLanguageSpy).toHaveBeenCalledTimes(1)
	})

	it('does not fall back to subtag when fallbackToSubtag is false', () => {
		const instance = kotori({ primary: 'en', secondaries: ['zh', 'ja'] })
		mockNavigatorLanguages(['zh-CN'])

		detectLanguage(instance, { fallbackToSubtag: false })

		expect(setLanguageSpy).not.toHaveBeenCalled()
	})

	it('prefers exact match over subtag fallback', () => {
		const instance = kotori({ primary: 'en', secondaries: ['zh', 'zh-TW'] })
		const setLanguageSpy = vi.spyOn(instance, 'setLanguage')
		mockNavigatorLanguages(['zh-TW'])

		detectLanguage(instance)

		expect(setLanguageSpy).toHaveBeenCalledWith('zh-TW')
		expect(setLanguageSpy).not.toHaveBeenCalledWith('zh')
	})

	it('falls back to subtag of second preference if first has no match', () => {
		mockNavigatorLanguages(['fr-FR', 'zh-CN'])

		detectLanguage(instance)

		expect(setLanguageSpy).toHaveBeenCalledWith('zh')
		expect(setLanguageSpy).toHaveBeenCalledTimes(1)
	})
})

// ============================
// no match
// ============================

describe('no match', () => {
	it('does not call setLanguage when no browser language matches', () => {
		mockNavigatorLanguages(['fr', 'de'])

		detectLanguage(instance)

		expect(setLanguageSpy).not.toHaveBeenCalled()
	})

	it('does not call setLanguage when browser languages is empty', () => {
		mockNavigatorLanguages([])

		detectLanguage(instance)

		expect(setLanguageSpy).not.toHaveBeenCalled()
	})

	it('does not call setLanguage when subtag does not match and fallbackToSubtag is true', () => {
		mockNavigatorLanguages(['fr-FR'])

		detectLanguage(instance)

		expect(setLanguageSpy).not.toHaveBeenCalled()
	})
})

// ============================
// called only once
// ============================

describe('called only once', () => {
	it('stops at first match and does not call setLanguage again', () => {
		mockNavigatorLanguages(['zh', 'ja', 'en'])

		detectLanguage(instance)

		expect(setLanguageSpy).toHaveBeenCalledTimes(1)
	})

	it('stops at first subtag match and does not continue', () => {
		mockNavigatorLanguages(['zh-CN', 'ja-JP'])

		detectLanguage(instance)

		expect(setLanguageSpy).toHaveBeenCalledWith('zh')
		expect(setLanguageSpy).toHaveBeenCalledTimes(1)
	})
})
